### ISSUE TITLE
Does not work with ui-bootstrap 1.+

### ISSUE THREAD

**Issue by sdesmond** [Joiler/ui-grid-edit-datepicker#1]
Using the Plunker in the description, if I change the Bootstrap UI version to 1.0.0, the demo no longer works.

**Comment by Joiler** [comment]
Current versions of [Angular UI Datepicker](https://angular-ui.github.io/bootstrap/) don't support Bootstrap 1.0.0 version. That's why CSS styles are not loaded correctly with Bootstrap 1.

**Comment by sdesmond** [comment]
Not sure if we're talking about two different things.  I'm talking about UI Bootstrap, not the Bootstrap stylesheet.  If I use your Plunker (http://plnkr.co/edit/4mNr86cN6wFOLYQ02QND) and change

`<script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.14.3.js"></script>`

to 

`<script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-1.0.0.js"></script>`

The datepicker popup does not show.

**Comment by Joiler** [comment]
This issue has been fixed. New Plunker link: http://plnkr.co/edit/l2ei2HJpqFR3rDa07haz
