### ISSUE TITLE
Not able to implement min/minDate and max/maxDate for this UI Grid Edit Datepicker!

### ISSUE THREAD

**Issue by rakiUK** [Joiler/ui-grid-edit-datepicker#4]
I have been trying to implement min/min-Date and max/max-Date for this UI Grid Edit DatePicker, but not successful. I really appreciate if you can navigate or redirect me to implement this below.
http://plnkr.co/edit/K64eD0COYBvwwZIq57wZ?p=preview.
And will be helpful to everybody if you can update the documentation accordingly.

**Comment by Joiler** [comment]
@rakiUK , Thanks, it's really necessary to add!
I added ability to pass Datepicker configuration object from Grid controller to directive. I updated Readme file. Plunker link: http://plnkr.co/edit/lMrVPfLuHfSgWmtlxG9G
Actually, it works only from Angular UI Grid 1.2.

**Comment by rakiUK** [comment]
@Joiler , That's Perfect. Thanks very much
