### ISSUE TITLE
button traduction is not working

### ISSUE THREAD

**Issue by mnaouali** [Joiler/ui-grid-edit-datepicker#8]
I tried using your solution for datepicker inside ui-grid  but when I tried translating the close, today and clear button I wasn't able to day that using the ususal methode like in angular ui-datepicker  I mean like this `close-text="{{\'lblClose\' | translate}}" current-text="{{\'lblToday\' | translate}}" clear-text="{{\'lblClear\' | translate}}"`
Would you please helping me get that fixed.

**Comment by Joiler** [comment]
@mnaouali , could you check the following Plunker example?http://plnkr.co/edit/qzpNX8tdA6mDhqeu090M?p=preview

I added Russian translations (see app.js for translating configuration) for these buttons (Today, Clear, Done) and it works correctly for me.

**Comment by mnaouali** [comment]
problem fixed by updating the directive
